[pytest]
pythonpath =
    .
    ..
# Folder test mặc định khi chạy `pytest` hoặc `make test`
testpaths =
    tests

# Cấu hình coverage/report mặc định
addopts =
    -v
    --tb=short
    --cov=app/api
    --cov=core.infra
    --cov=app/tools
    --cov-config=.coveragerc
    --cov-report=term-missing:skip-covered
    --cov-report=html:tests/htmlcov/coverage
    --cov-report=xml:tests/coverage.xml
    --cov-fail-under=100
    --html=tests/htmlcov/pytest-report.html
    --self-contained-html
    --junitxml=tests/htmlcov/junit.xml

# Quy ước tên file/class/function test
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# asyncio mode
asyncio_mode = auto
