[pytest]
pythonpath =
    .
    ..
testpaths =
    tests
addopts =
    -v
    --tb=short
    --cov=core.grpc_server
    --cov-config=.coveragerc
    --cov-report=term-missing:skip-covered
    --cov-report=html:tests/htmlcov/coverage
    --cov-report=xml:tests/coverage.xml
    --cov-fail-under=100
    --html=tests/htmlcov/pytest-report.html
    --self-contained-html
    --junitxml=tests/htmlcov/junit.xml
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
