apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger-onflow
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: 'loki'
        filterBySpanID: false
        filterByTraceID: false
        query: '|= "$${__trace.traceId}"'
